/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ImageFormatKind {
  Png = 0,
  Jpeg = 1,
  Bmp = 2,
}
export declare class Clipboard {
  static make(): Clipboard
  /**
   * Copy text to the clipboard. Has special handling for WSL and SSH sessions, otherwise
   * falls back to the cross-platform `clipboard` crate
   */
  setText(text: string): void
  getText(): string | null
  getTextAsync(): Promise<string>
  readFiles(): Array<string> | null
  writeFiles(files: Array<string>): boolean
  readHtml(): string | null
  writeHtml(html: string): boolean
  getAllKinds(): Array<string> | null
  readImage(kind?: ImageFormatKind | undefined | null): Buffer | null
  writeImageExn(img: Buffer): boolean
  writeImage(img: Buffer): boolean
  readImageAsync(kind?: ImageFormatKind | undefined | null): Promise<Buffer>
  writeImageAsync(img: Buffer, signal?: AbortSignal | undefined | null): Promise<boolean>
}
